import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="top-nav sticky top-0 z-50">
          <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-3">
            <a href="/" className="site-title text-xl font-semibold">
              Martina Belotti Cooklin
            </a>
            <nav>
              <ul className="flex gap-2">
                <li>
                  <a href="/" className="px-4 py-2 sage-text font-medium">
                    About Me
                  </a>
                </li>
                <li>
                  <a href="/works" className="px-4 py-2 sage-text font-medium">
                    Works
                  </a>
                </li>
                <li>
                  <a href="/resources" className="px-4 py-2 sage-text font-medium">
                    Resources
                  </a>
                </li>
                <li>
                  <a href="/events" className="px-4 py-2 sage-text font-medium">
                    Events
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
